
export const UI_TEXT = {
    appTitle: 'ReptileGuard',
    identify: 'Identify Reptile',
    report: 'Report Sighting',
    dashboard: 'Dashboard',
    myReports: 'My Reports',
    allReports: 'All Reports',
    officerMode: 'Wildlife Officer',
    citizenMode: 'Citizen Mode',
    uploadImage: 'Upload or Capture Image',
    analyzing: 'Analyzing...',
    identifyBtn: 'Identify',
    venomous: 'Venomous',
    nonVenomous: 'Non-Venomous',
    precautions: 'Safety Precautions',
    submitReport: 'Submit Sighting Report',
    downloadPdf: 'Download Report (PDF)',
    status: 'Status',
    location: 'Location',
    viewDetails: 'View Details',
    rescueStatus: 'Rescue Status',
    updateStatus: 'Update Status',
    officerNotes: 'Officer Notes',
    save: 'Save',
    dangerLevel: 'Danger Level',
    scientificName: 'Scientific Name',
    description: 'Description',
    pending: 'Pending Action',
    assigned: 'Officer Assigned',
    rescued: 'Rescued',
    released: 'Released to Wild',
    falseAlarm: 'False Alarm',
    noReports: 'No reports found.',
    welcome: 'Reptile Identification and Management System for Peri-Urban Wildlife Conservation',
    welcomeSub: 'Peri-Urban Wildlife Conservation',
    switchRole: 'Switch Role',
    heroTitle: 'Protect Yourself, Preserve Wildlife.',
    heroSub: 'Reptile Identification and Management System for Peri-Urban Wildlife Conservation',
    login: 'Login',
    signup: 'Sign Up',
    welcomeBack: 'Welcome Back',
    joinTheMission: 'Join the Mission',
    fullName: 'Full Name',
    email: 'Email Address',
    password: 'Password',
    signInBtn: 'Sign In Now',
    signUpBtn: 'Create My Account',
    guestAccessBtn: 'Guest Instant Access',
    noAccount: "Don't have an account?",
    alreadyMember: 'Already a member?',
    registerNow: 'Register Account',
    loginNow: 'Login Securely',
    logout: 'Logout',
    guest: 'Guest',
    citizen: 'Citizen',
    mandatoryProof: 'Mandatory Proof (Image)',
    uploadProof: 'Upload Rescue/Release Photo',
    proofError: 'Please upload proof image first.',
    state: 'State',
    district: 'District',
    taluk: 'Taluk',
    settings: 'Settings',
    dataExport: 'Collected Data',
    filterByRegion: 'Filter by Region',
    rescuePhoto: 'Rescue Photo',
    enterDetails: 'Enter Location Details'
};
